### ISSUE TITLE
error with ungrib.exe

### ISSUE THREAD

**Issue by dlebauer** [ebimodeling/wrf-downscaling#1]
@brightfan reports this error when trying to run `ungrib.exe`:

``` sh
*** Starting program ungrib.exe ***
Start_date =  1987-09-30_12:00:00 ,      End_date = 1987-09-30_18:00:00
output format is WPS
Path to intermediate files is ./
ERROR: Grib2 file or date problem, stopping in edition_num.
```

In order for Scott to assist, this issue should be updated with:
- description of exactly what it is you are trying to do, 
- the namelist.wps (can be copy/pasted [to a gist](https://gist.github.com/) or committed to the repository)
- output from `ls -l` on the directory,

**Comment by Jipson-Johnson** [comment]
I link the data files link this  /link_grib.csh /home/user/Documents/Build_WRF/DATA/datafiles/\*  and then i gave run for ./ungrib.exe. At that time  i got the following error :
 **\* Starting program ungrib.exe ***
Start_date = 2011-04-25_00:00:00 , End_date = 2011-04-26_00:00:00
output format is WPS
Path to intermediate files is ./
ERROR: Grib2 file or date problem, stopping in edition_num.)

Actually i am using WRF3.6 version , I downloaded 26th April 2011 data and when extracted i got fnl_20110425_00_00.grib2.nc to fnl_20110426_00_00.grib2.nc files. 
But i can run run ungrib.exe when using data file ending with .grib1 only(eg: fnl_20090511_18_00.grib1) . Is it necessary to convert  fnl_20110425_00_00.grib2.nc file to fnl_20110425_00_00.grib1 file ??
Please help me, Thanks

**Comment by dlebauer** [comment]
@Jipson-Johnson can you provide a reproducible example? Are you using code from this repository? What computer are you trying to run it on?

**Comment by Jipson-Johnson** [comment]
I am using Ubuntu 14.04. Reproducible example means?

**Comment by dlebauer** [comment]
See 'how to file a bug report
http://www.softwaretestinghelp.com/how-to-write-good-bug-report/

Also, thIs is not a WRF repository, although we have a copy of the source
code. Have you tried the WRF users guide?
http://www.wrf-model.org/users/users.php they have links to support lists.

**Comment by jipsonjohnson777** [comment]
@dlebauer  Can you please give a solution for this error ?

**Comment by dlebauer** [comment]
@jipsonjohnson777 no, sorry, I don't have a solution
